#!/bin/sh

die() {
    echo "$@" >&2
    exit 1
}

SCRIPTS_DIR="$(cd $(dirname $0) && pwd)"
GIT_CLONE_DOTFILES="$SCRIPTS_DIR/git-clone-dotfiles"
MIRROR_ALL_GITHUB_REPOS="$SCRIPTS_DIR/mirror-all-github-repos"

# Clone dotfiles
mkdir -p ~/git/github
cd ~/git/github
$GIT_CLONE_DOTFILES
cd ~/git
$MIRROR_ALL_GITHUB_REPOS    # this skips 'dotfiles' because it already exists.

mkdir -p ~/git/+public
$MIRROR_ALL_GITHUB_REPOS --bare
