#!/bin/sh

progname="`basename $0`"
path_config="/etc/$progname/config"

usage() {
    echo "service $progname [start|stop|restart|status]" >&2
    exit 1
}
load_config() {
    [ -e "$path_config" ] && . "$path_config"
}
get_daemon_pid() {
    pgrep $progname
}
is_starting() {
    [ ! -z "`get_daemon_pid`" ]
}

do_start() {
    echo "Starting $progname..."
    load_config
    if [ -z "$GIT_DAEMON_DAEMON_BASE_PATH" ]; then
        base_path=
    else
        base_path="--base-path=$GIT_DAEMON_DAEMON_BASE_PATH"
    fi
    git daemon \
        --export-all \
        $base_path \
        >/dev/null 2>&1 &
}
do_stop() {
    echo "Stopping $progname..."
    killall -q $progname
}
do_restart() {
    echo "Restarting $progname..."
    do_stop
    do_start
}
do_status() {
    if is_starting; then
        pid=`get_daemon_pid`
        echo "Running as pid $pid..."
    else
        echo "Not running."
    fi
}


case "$1" in
    start|stop|restart|status)
    do_$1
    ;;
    *)
    usage
    ;;
esac
