#!/bin/sh


doit() {
    # local
    for i in perl5 perlbrew; do
        if [ ! -e $i ]; then
            mkdir -p local/$i
        fi
    done

    # vcs
    for i in git hg svn darcs; do
        if [ ! -e $i ]; then
            mkdir -p vcs/$i
            ln -s vcs/$i $i
        fi
    done

    # tmp
    for i in down trash/samba build; do
        if [ ! -e $i ]; then
            mkdir -p tmp/$i
            ln -s tmp/$i $i
        fi
    done

    # make symlinks from (to?) Dropbox
    if [ -e Dropbox ]; then
        for i in scratch memo diary site; do
            [ ! -e "$i" ] && ln -s Dropbox/$i $i
        done
        if [ -d git/tyru.github.com -a -d site ]; then
            ln -s git/tyru.github.com site/tyru.github.com
        fi
    fi
}
(cd && doit)
