#!/bin/sh

# Be careful, this must not work well
# even if there was already setup repo.

die() {
    echo "$@" >&2
    exit 1
}


cd || die "can't chdir to home directory."

[ -d Dropbox ] && ln -s Dropbox/memo memo

mkdir -p vcs/git vcs/hg vcs/svn vcs/darcs
ln -s vcs/git git
ln -s vcs/hg hg
ln -s vcs/svn svn
ln -s vcs/darcs darcs

mkdir -p tmp/build tmp/down tmp/trash/samba
ln -s tmp/build build
ln -s tmp/down down

[ -d git/hatenadiary-tyru ] && ln -s git/hatenadiary-tyru diary
