#!/bin/sh

# Be careful, this must not work well
# even if there was already setup repo.

die() {
    echo "$@" >&2
    exit 1
}


cd || die "can't chdir to home directory."

[ ! -e memo ] && ln -s Dropbox/memo memo

mkdir -p vcs/git vcs/hg vcs/svn vcs/darcs
[ ! -e git ] && ln -s vcs/git git
[ ! -e hg ] && ln -s vcs/hg hg
[ ! -e svn ] && ln -s vcs/svn svn
[ ! -e darcs ] && ln -s vcs/darcs darcs

mkdir -p tmp/build tmp/down tmp/trash/samba
[ ! -e build ] && ln -s tmp/build build
[ ! -e down ] && ln -s tmp/down down

[ ! -e diary ] && ln -s git/hatenadiary-tyru diary
