#!/bin/sh

# Be careful, this must not work well
# even if there was already setup repo.

# Clone dotfiles under this directory.
DIR="$HOME/git"

die() {
    echo "$@" >&2
    exit 1
}


mkdir -p $DIR
cd $DIR || die "can't chdir to '$DIR'."

if [ -d dotfiles ]; then
    cd dotfiles || die "can't chdir to 'dotfiles'."
    git pull origin master
    exit $?
fi

git clone git://github.com/tyru/dotfiles.git
cd dotfiles || die "can't chdir to 'dotfiles'.";

git submodule update --init

# Checkout HEAD branch.
git submodule foreach 'git checkout master; true'
# TODO: This will be changed in near future.
(cd dotfiles/.vim/bundle/skk.vim && git checkout azik)

git submodule foreach 'git pull origin master; true'

# Create remote 'me', 'bare'.
git submodule foreach 'git remote add me git@github.com:tyru/`basename $path`.git; true'
git submodule foreach 'git remote add bare ~/git/+public/github/`basename $path`.git; true'
# Only './tools' has different name from github repo.
# it is 'dotto'.
(cd tools && {
    git remote rm me;
    git remote rm bare;
    git remote add me git@github.com:tyru/dotto.git;
    git remote add bare ~/git/+public/github/dotto.git;
})
