#!/bin/sh


doit() {
    # local
    for i in perl5 perlbrew; do
        if [ ! -e $i ]; then
            mkdir -p local/$i
        fi
    done

    # vcs
    for i in git hg svn darcs; do
        if [ ! -e $i ]; then
            mkdir -p vcs/$i
            ln -s vcs/$i $i
        fi
    done

    # tmp
    mkdir -p tmp
    mkdir -p trash/samba
    mkdir -p down

    # memo
    [ ! -e memo ] && [ -e Dropbox ] && ln -s Dropbox/memo memo

    # diary
    [ ! -e diary ] && [ -e git/hatenadiary-tyru ] && ln -s git/hatenadiary-tyru diary
}
(cd && doit)
