#!/bin/sh


doit() {
    # local
    for i in perl5 perlbrew; do
        if [ ! -e $i ]; then
            mkdir -p local/$i
        fi
    done

    # vcs
    for i in git hg svn darcs; do
        if [ ! -e $i ]; then
            mkdir -p vcs/$i
            ln -s vcs/$i $i
        fi
    done

    # tmp
    mkdir -p tmp
    mkdir -p trash/samba
    mkdir -p down

    # make symlinks from (to?) Dropbox
    if [ -e Dropbox ]; then
        for i in scratch memo diary; do
            [ ! -e "$i" ] && ln -s Dropbox/$i $i
        done
    fi
}
(cd && doit)
