#!/bin/sh

# Be careful, this must not work well
# even if there was already setup repo.

die() {
    echo "$@" >&2
    exit 1
}


cd $HOME/git || die "can't chdir to '$DIR'."

if [ -d dotfiles ]; then
    # Update only.
    cd dotfiles || die "can't chdir to 'dotfiles'."
    git pull origin master
    exit $?
fi

git clone git://github.com/tyru/dotfiles.git
cd dotfiles || die "can't chdir to 'dotfiles'.";

git submodule update --init

# Checkout HEAD branch.
git submodule foreach 'git checkout master; git pull origin master; true'

# Create remote 'me', 'backup'.
git submodule foreach 'git remote add me git@github.com:tyru/`basename $path`.git; true'
git submodule foreach 'git remote add backup ~/git/+public/github/`basename $path`.git; true'
# Only './tools' has different name (dotto) from github repo.
doit() {
    git remote rm me
    git remote rm backup
    git remote add me git@github.com:tyru/dotto.git
    git remote add backup ~/git/+public/github/dotto.git
}
(cd tools && doit)
