#!/bin/sh

cpanminus_installed() {
    perldoc -l App::cpanminus >/dev/null 2>&1
}

if ! cpanminus_installed; then
    wget --no-check-certificate http://xrl.us/cpanm || exit $?
    chmod +x cpanm
    ./cpanm --self-upgrade
    rm cpanm
fi
